/**
* This file is generated by @vramework/cli@0.5.4 on 2024-10-26T17:20:19.528Z
*/

/**
* This is used to provide the application types in the typescript project
*/
  
import { CoreAPIFunction, CoreAPIPermission, CoreAPIRoute, addCoreRoute, AssertRouteParams } from '@vramework/core'
  
import { type UserSession } from './application-types'
import { type Services } from './application-types'

export type APIFunctionSessionless<In, Out, RequiredServices = Services> = CoreAPIFunction<In, Out, RequiredServices, UserSession>
export type APIFunction<In, Out, RequiredServices = Services> = CoreAPIFunction<In, Out, RequiredServices, UserSession>
export type APIPermission<In, RequiredServices = Services> = CoreAPIPermission<In, RequiredServices, UserSession>

type APIRoute<In, Out, Route extends string> = CoreAPIRoute<In, Out, Route, APIFunction<In, Out>, APIFunctionSessionless<In, Out>, APIPermission<In>>

export const addRoute = <In, Out, Route extends string>(route: APIRoute<In, Out, Route> & AssertRouteParams<In, Route>) => {
  addCoreRoute(route as any)
}
